// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CWrapper_distance
List CWrapper_distance(std::string file_name_, std::string word_, int size_);
RcppExport SEXP word2vecr_CWrapper_distance(SEXP file_name_SEXP, SEXP word_SEXP, SEXP size_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type file_name_(file_name_SEXP);
    Rcpp::traits::input_parameter< std::string >::type word_(word_SEXP);
    Rcpp::traits::input_parameter< int >::type size_(size_SEXP);
    __result = Rcpp::wrap(CWrapper_distance(file_name_, word_, size_));
    return __result;
END_RCPP
}
// CWrapper_word2phrase
void CWrapper_word2phrase(std::string train_file_, std::string output_file_, int min_count, double threshold);
RcppExport SEXP word2vecr_CWrapper_word2phrase(SEXP train_file_SEXP, SEXP output_file_SEXP, SEXP min_countSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type train_file_(train_file_SEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file_(output_file_SEXP);
    Rcpp::traits::input_parameter< int >::type min_count(min_countSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    CWrapper_word2phrase(train_file_, output_file_, min_count, threshold);
    return R_NilValue;
END_RCPP
}
// CWrapper_word2vec
void CWrapper_word2vec(std::string train_file_, std::string output_file_, int binary_, int size_);
RcppExport SEXP word2vecr_CWrapper_word2vec(SEXP train_file_SEXP, SEXP output_file_SEXP, SEXP binary_SEXP, SEXP size_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type train_file_(train_file_SEXP);
    Rcpp::traits::input_parameter< std::string >::type output_file_(output_file_SEXP);
    Rcpp::traits::input_parameter< int >::type binary_(binary_SEXP);
    Rcpp::traits::input_parameter< int >::type size_(size_SEXP);
    CWrapper_word2vec(train_file_, output_file_, binary_, size_);
    return R_NilValue;
END_RCPP
}
