# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib word2vecr
CWrapper_distance <- function(file_name_, word_, size_) {
    .Call('word2vecr_CWrapper_distance', PACKAGE = 'word2vecr', file_name_, word_, size_)
}

#' @useDynLib word2vecr
CWrapper_word2phrase <- function(train_file_, output_file_, min_count, threshold) {
    invisible(.Call('word2vecr_CWrapper_word2phrase', PACKAGE = 'word2vecr', train_file_, output_file_, min_count, threshold))
}

#' @useDynLib word2vecr
CWrapper_word2vec <- function(train_file_, output_file_, binary_ = 1L, size_ = 100L) {
    invisible(.Call('word2vecr_CWrapper_word2vec', PACKAGE = 'word2vecr', train_file_, output_file_, binary_, size_))
}

